#!/bin/bash

set -eux

ASSERT_GEM_VERSION=3.2.28

echo "Testing runtime compability"

# shellcheck disable=1091
source "/var/vcap/packages/ruby-3.0.2-r0.65.0/bosh/runtime.env"
ruby -e 'puts "test"'

echo "Testing compile compability"

# shellcheck disable=1091
source "/var/vcap/packages/ruby-3.0-test/bosh/runtime.env"
cd /var/vcap/packages/ruby-3.0-test/
bundle exec thin start &
sleep 3
curl http://localhost:3000 | grep test
kill -9 $!

gems_version=$(bundle exec gem -v)
if [[ $gems_version == *"$ASSERT_GEM_VERSION"* ]]; then
  echo "found correct rubygems version $gems_version"
else
  echo "wrong rubygems version: $gems_version"
  exit 1
fi
