---
name: test

releases:
- name: ruby-release
  version: latest

stemcells:
- alias: default
  os: ((stemcell))
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: ruby-thin-server
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: ((ruby-test-package))
    release: ruby-release
    properties: {}
  vm_type: default
  stemcell: default
  networks:
  - name: default
