#!/bin/bash

set -eux

ASSERT_GEM_VERSION="4.0.9"

echo "Testing runtime compatibility"

# shellcheck disable=1091
source "/var/vcap/packages/ruby-4.0/bosh/runtime.env"
ruby -e 'puts "test"'

if [ $(ruby -e 'require "yaml"; puts({a: "b\n\n\n"}.to_yaml)' | grep "\.\.\.") ]; then
  echo "Found unpatched libyaml"
  exit 1
fi

echo "Testing compile compatibility"

# shellcheck disable=1091
source "/var/vcap/packages/ruby-4.0-test/bosh/runtime.env"
cd "/var/vcap/packages/ruby-4.0-test/"
export PUMA_DEFAULT_PORT=9292
export CURL_TIMEOUT_SECONDS=5

bundle exec puma --port "${PUMA_DEFAULT_PORT}" &

sleep 3

curl --connect-timeout "${CURL_TIMEOUT_SECONDS}" "http://localhost:${PUMA_DEFAULT_PORT}" | grep test

kill -9 $!

gems_version=$(bundle exec gem -v)
if [[ $gems_version == *"$ASSERT_GEM_VERSION"* ]]; then
  echo "found correct rubygems version $gems_version"
else
  echo "wrong rubygems version: $gems_version"
  exit 1
fi
