#@ load("@ytt:data", "data")
#@yaml/text-templated-strings
jobs:
- name: manually-release
  serial: true
  serial_groups:
    - bump
  plan:
  - in_parallel:
    - get: ruby-release
    - get: semver
      params:
        bump: minor
    - get: bosh-shared-ci
  - task: finalize
    file: bosh-shared-ci/tasks/release/create-final-release.yml
    input_mapping:
      release_repo: ruby-release
      version: semver
    params:
      GIT_USER_NAME: CI Bot
      GIT_USER_EMAIL: bots@cloudfoundry.org
      PRIVATE_YML: |
        ---
        blobstore:
          provider: gcs
          options:
            credentials_source: static
            json_key: '((gcp_json_key))'
  - in_parallel:
    - put: semver
      params:
        file: semver/version
    - put: ruby-release
      params:
        rebase: true
        repository: release_repo
        tag: release_metadata/tag-name

#@ for ruby in data.values.rubies:
- name: test-(@= ruby.version @)
  serial: true
  plan:
  - in_parallel:
    - get: ruby-release
      trigger: true
    - get: stemcell
      resource: (@= ruby.stemcell @)
      trigger: true
  - task: test
    privileged: true
    timeout: 2h
    params:
      RUBY_VERSION: "(@= ruby.version @)"
      STEMCELL: "(@= ruby.stemcell @)"
    file: ruby-release/ci/tasks/test.yml

- name: bump-(@= ruby.version @)
  serial: true
  serial_groups:
    - bump
  plan:
  - in_parallel:
    - get: ruby
      resource: ruby-(@= ruby.version @)
      trigger: true
    - get: rubygems
      resource: rubygems-(@= ruby.rubygems @)
      trigger: true
    - get: libyaml
      resource: yaml-(@= ruby.libyaml @)
      trigger: true
    - get: ruby-release
    - get: stemcell
      resource: (@= ruby.stemcell @)
    - get: bosh-src
    - get: semver
      params:
        bump: minor
    - get: bosh-shared-ci
  - task: bump
    file: ruby-release/ci/tasks/bump.yml
    params:
      PRIVATE_YML: |
        ---
        blobstore:
          provider: gcs
          options:
            credentials_source: static
            json_key: '((gcp_json_key))'
      RUBY_VERSION: "(@= ruby.version @)"
      RUBYGEMS_VERSION: "(@= ruby.rubygems @)"
      LIBYAML_VERSION: "(@= ruby.libyaml @)"
  - task: test-bumped
    privileged: true
    file: ruby-release/ci/tasks/test.yml
    params:
      RUBY_VERSION: "(@= ruby.version @)"
      STEMCELL: "(@= ruby.stemcell @)"
  - task: finalize
    file: bosh-shared-ci/tasks/release/create-final-release.yml
    input_mapping:
      release_repo: ruby-release
      version: semver
    params:
      GIT_USER_NAME: CI Bot
      GIT_USER_EMAIL: bots@cloudfoundry.org
      PRIVATE_YML: |
        ---
        blobstore:
          provider: gcs
          options:
            credentials_source: static
            json_key: '((gcp_json_key))'
  - in_parallel:
    - put: semver
      params:
        file: semver/version
    - put: ruby-release
      params:
        rebase: true
        repository: release_repo
        tag: release_metadata/tag-name
#@ end
- name: build-docker-image
  plan:
  - in_parallel:
    - get: ruby-release
      trigger: true
    - task: build-docker-args
      file: bosh-ecosystem-dockerfile/docker/build-args.yml
      image: ubuntu-registry-image
  - put: ruby-release-image
    params:
      build: ruby-release
      dockerfile: ruby-release/ci/docker/Dockerfile
      build_args_file: docker-build-args/docker-build-args.json
    get_params:
      skip_download: true

#@yaml/text-templated-strings
resources:
- name: bosh-shared-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-shared-ci.git
    private_key: ((github_deploy_key_bosh-shared-ci.private_key))

- name: bosh-src
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh.git

- name: ruby-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-package-ruby-release.git
    branch: main
    private_key: ((github_deploy_key_ruby-release.private_key))

- name: ubuntu-jammy
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-jammy-go_agent

- name: semver
  type: semver
  source:
    initial_version: "0.187.0"
    driver: git
    uri: git@github.com:cloudfoundry/bosh-package-ruby-release.git
    branch: release-semver
    file: VERSION
    private_key: ((github_deploy_key_ruby-release.private_key))

#@ for rubygems in data.values.rubygems:
- name: rubygems-(@= rubygems.version @)
  type: dynamic-metalink
  source:
    version: "(@= rubygems.version @).x"
    version_check: |
     git ls-remote --tags https://github.com/rubygems/rubygems.git \
       | cut -f2 \
       | grep -v '\^{}' \
       | grep -E '^refs/tags/.+$' \
       | sed  -E 's/^refs\/tags\/(.+)$/\1/'  \
       | sed  's/^v//' \
       | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'
    metalink_get: |
      export name="rubygems-${version}.tgz"
      export url="https://rubygems.org/rubygems/rubygems-${version}.tgz"
      export size=$( curl --silent --head "$url" | grep Content-Length | awk '{ print $2 }' | tr -cd '[:digit:]' )
      jq -n '
      {
       "files": [
        {
         "name": env.name,
         "urls": [ { "url": env.url } ],
         "size": env.size | tonumber
        }
       ]
      }'
#@ end

#@ for libyaml in data.values.libyamls:
- name: yaml-(@= libyaml.version @)
  type: dynamic-metalink
  source:
    version: "(@= libyaml.version @).x"
    version_check: |
     git ls-remote --tags https://github.com/yaml/libyaml.git \
       | cut  -f2 \
       | grep -v '\^{}' \
       | grep -E '^refs/tags/.+$' \
       | sed  -E 's/^refs\/tags\/(.+)$/\1/'  \
       | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'
    metalink_get: |
      export name="yaml-${version}.tar.gz"
      export url="http://pyyaml.org/download/libyaml/yaml-${version}.tar.gz"
      export size=$( curl --silent --head "$url" | grep Content-Length | awk '{ print $2 }' | tr -cd '[:digit:]' )
      jq -n '
      {
       "files": [
        {
         "name": env.name,
         "urls": [ { "url": env.url } ],
         "size": env.size | tonumber
        }
       ]
      }'
#@ end

#@ for ruby in data.values.rubies:
- name: ruby-(@= ruby.version @)
  type: dynamic-metalink
  source:
    version: "(@= ruby.version @).x"
    version_check: |
      curl --silent --location https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/stable.txt
    metalink_get: |
      export name="ruby-${version}.tar.gz"
      export url="http://cache.ruby-lang.org/pub/ruby/(@= ruby.version @)/${name}"
      export sha256="$(curl --silent --location https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/checksums.sha256 | grep ruby-${version}.tar.gz | awk {'print $1'})"
      export size="$(curl --silent --head "$url" | grep -i Content-Length | awk '{ print $2 }' | tr -cd '[:digit:]')"
      jq -n '
      {
       "files": [
        {
         "name": env.name,
         "urls": [ { "url": env.url } ],
         "hashes": [{ "type": "sha-256", "hash": env.sha256 }],
         "size": env.size | tonumber
        }
       ]
      }'
#@ end

- name: ubuntu--registry-image
  type: registry-image
  source:
    repository: ubuntu
    username: ((docker.username))
    password: ((docker.password))

- name: ruby-release-image
  type: docker-image
  source:
    repository: bosh/ruby-release
    username: ((bosh-dockerhub.username))
    password: ((bosh-dockerhub.password))

resource_types:
- name: dynamic-metalink
  type: docker-image
  source:
    repository: dpb587/dynamic-metalink-resource
- name: semver
  type: docker-image
  source:
    repository: concourse/semver-resource
    tag: 1.6
